### ISSUE TITLE
Why is this list not listed in the main awesome list?

### ISSUE THREAD

**Issue by wansaleh** [miziomon/awesome-wordpress#19]
Hi.

The question's self explanatory. Why not listed in @sindresorhus's [awesome list](https://github.com/sindresorhus/awesome)?

**Comment by miziomon** [comment]
I will do a pull request to @sindresorhus's awesome list 
Thanks for the suggest

**Comment by sindresorhus** [comment]
Make sure you read and follow: https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md
