### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by picocodes** [miziomon/awesome-wordpress#27]
Since @miziomon hasn't been active on Github for a while; I decided to create a [fork of the repo](https://github.com/picocodes/awesome-wordpress).

Send in your pull requests as we create one of the most comprehensive awesome WordPress list.

**Comment by widoz** [comment]
following, want to know if @miziomon don't want to keep curate this repo. It's useless have double repo for this kind of data.

**Comment by miziomon** [comment]
@picocodes I'm here but now I'm busy and this repo is not in my priority. I need to do some work to check, fix and clean the pull request and at this time I don't aknow when I will do
... of course you can do what you want
